version: '3.1'

services:

  nginx:
    container_name: exteam-app
    image: exteam
    build: '.'
    ports:
      - "80:80"
      - "443:443"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge